### ISSUE TITLE
feat(userName): 사용자 이름 API 구현

### ISSUE THREAD

**Issue by chulheungkim** [TIP-ZIP/TIPZIP_FE#38]
## Tasks

- [x] 닉네임 중복 검사 API 연결
- [x] 닉네임 저장 API 연결
- [x] 위의 2가지 API response를 기준으로 error 처리
