### ISSUE TITLE
style(global): 글로벌 스타일 가이드 작성

### ISSUE THREAD

**Issue by chulheungkim** [TIP-ZIP/TIPZIP_FE#4]
## Tasks

- [x] Typography, Color Palette -  각각 `typography.ts`, `colors.ts` 파일에 작성
- [x] `theme.ts` 파일에서 `colors`, `fontStyles` import

## Additional Task

- [ ] `layout` 디렉토리 `src/components/layout`에서 `src/layout`으로 위치 변경
