### ISSUE TITLE
feat(Login): 온보딩 페이지 및 로그인 페이지 UI 구현

### ISSUE THREAD

**Issue by chulheungkim** [TIP-ZIP/TIPZIP_FE#6]
## Tasks

- [x] 첫 화면 구현 및 일정 시간 지나면 로그인 화면 이동 구현
- [x] 로그인 페이지 구현 (소셜 로그인 Kakao, Naver, Google)
- [x] 소셜 로그인 성공 이후 사용자 이름 설정 페이지 UI 구현
